name: Workflow Testing

on:
  workflow_dispatch:
  push: 
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  greet-test:
    env:
      MY_ENV: "Mike Hawk"
    runs-on: ubuntu-latest
    steps:
     - name: Greet the User
       run: echo "Hi there, user!"
     - name: Show the directory before checking the code
       run: ls -l
     - name: Check out the code
       uses: actions/checkout@v3
     - name: Show the directory after checking the code
       run: ls -l
     - name: Run a multi-line script to show env variables
       run: 
         echo "Hello $MY_ENV"
         echo "Hello $GITHUB_ACTOR"
